### ISSUE TITLE
Misc improvements

### ISSUE THREAD

**Issue by Torsdan** [NeonRD1/MusicBot#52]
/hug - :heartmoden: doesn't seem to exist.
Can we change the name of Sigma-chan to the bots name in channel?
Can the invoking request for songs be auto-cleared too?
-If you want to keep a record of who requested the song, maybe "@Torsdan enqueued .." or "Torsdan enqueued .."
- "@Torsdan enqueued Vicetone - Nevada."

I've just wanted to be able to keep the channel clean.

> Torsdan#0656: !hug <@331760800807256064>
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "E:\DiscordBot\Sigma-Kizuna-master\Sigma-Kizuna-master\musicbot\bot.py", line 3417, in on_message
    response = await handler(**handler_kwargs)
  File "E:\DiscordBot\Sigma-Kizuna-master\Sigma-Kizuna-master\musicbot\bot.py", line 1271, in cmd_hug
    await self.safe_send_file(channel, None, thumbnail, expire_in=30)
  File "E:\DiscordBot\Sigma-Kizuna-master\Sigma-Kizuna-master\musicbot\bot.py", line 950, in safe_send_file
    msg = await self.send_file(dest, fp, content=content, tts=tts)
  File "C:\Users\Torsdan\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 1226, in send_file
    with open(fp, 'rb') as f:
PermissionError: [Errno 13] Permission denied: 'data/gifs/audio_cache'

Not quite sure what the above error is about. Is that an error to do with Text to Speech (tts)?

**Comment by NeonLights10** [comment]
-invoking request: those can be changed by adding or removing commands from the retain_commands config field
-record of who requested song: you can have now_playing_mentions already, I will not implement requests to reduce mention spam.
-Going to implement the dynamic name in %help etc.
As for the error, it is probably related to the failure to load gifs, but you also seem to have permission errors for accessing files. I'll remove that part for now.

**Comment by Torsdan** [comment]
Thank you, I wasn't aware that retain_commands did that, maybe for others a quick comment in the config?

**Comment by NeonLights10** [comment]
Everything should be fixed now, got around to implementing the dynamic name in dev branch for now.
